kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: OUTPUT_TAG
    description: The output image tag
    default: dev
    required: true
  - name: DEPLOYMENT_NAME
    required: true
    description: the name of the components
  - name: NAMESPACE
    required: true
    default: c183df-dev
    description: the spacespace to deploy to
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      selector:
        app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
        deploymentConfig: ${DEPLOYMENT_NAME}
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
            deploymentConfig: ${DEPLOYMENT_NAME}
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${DEPLOYMENT_NAME}:${OUTPUT_TAG}
              name: ${DEPLOYMENT_NAME}
              env:
                - name: PORT
                  value: '3000'
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources: {}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${DEPLOYMENT_NAME}
            from:
              kind: ImageStreamTag
              name: '${DEPLOYMENT_NAME}:${OUTPUT_TAG}'
              namespace: ${NAMESPACE}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
        version: ${OUTPUT_TAG}
      name: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: web
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
        version: ${OUTPUT_TAG}
      name: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        app: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
        version: ${OUTPUT_TAG}
      name: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
      namespace: ${NAMESPACE}
    spec:
      host: ""
      port:
        targetPort: 3000
      to:
        kind: Service
        name: ${DEPLOYMENT_NAME}-${OUTPUT_TAG}
        weight: 100
      wildcardPolicy: None
    status:
      ingress: null