kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    default: c183df-dev
    description: the spacespace to deploy to
  - name: TS_NAME
    required: true
    description: the name of the service component
  - name: OUTPUT_TAG
    description: The output image tag
    default: dev
    required: true
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-f5-ingress
      namespace: ${NAMESPACE}
    spec:
      podSelector:
        matchLabels:
          name: ${TS_NAME}-${OUTPUT_TAG}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress