kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    default: c183df-dev
    description: the spacespace to deploy to
  - name: TSC_NAME
    required: true
    description: the name of the service component
objects:
  - apiVersion: porter.devops.gov.bc.ca/v1alpha1
    kind: TransportServerClaim
    metadata:
      name: ${TSC_NAME}-tsc
      namespace: ${NAMESPACE}
    spec:
      monitor:
        interval: 10
        timeout: 10
        type: tcp
      service: ${TSC_NAME}
      servicePort: 3000